### ISSUE TITLE
Bind to public

### ISSUE THREAD

**Issue by aretsmarvin** [gabrielresende/pubquiz#1]
Hi,

How can I correctly set it up for public? You now only can connect using localhost.

**Comment by gabrielresende** [comment]
Hi @aretsmarvin. You can run the server with option `-b 0.0.0.0`, this will listen to all interfaces instead of just localhost:

```
$ rails s -b 0.0.0.0
```

Hope that helps! 👍

**Comment by gabrielresende** [comment]
Hi @aretsmarvin. You can run the server with option `-b 0.0.0.0`, this will listen to all interfaces instead of just localhost:

```
$ rails s -b 0.0.0.0
```

Hope that helps! 👍

**Comment by aretsmarvin** [comment]
Yes that worked. Was to soon with my question. Found it on internet already. I am new to ruby/rails. So it's a little bit researching for me. Struggling with Cloudflare/SSL right now 
App looks very nice 👍
