### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by aretsmarvin** [gabrielresende/pubquiz#2]
Thanks for this amazing tool.

I want to use it tomorrow night (over the internet, due to current Covid situation). 

For preventing browsers to complain about SSL, I want to enable SSL. But this doesn't work for me. 

Usually I use Cloudflare for SSL. But when I say force_ssl = true in the config, I can't load it using SSL.

You know much more about ruby/rails. Maybe you have some tips for running it with SSL?

**Comment by gabrielresende** [comment]
Hi @aretsmarvin,

The option `force_ssl = true` will only [force the application to use SSL](https://stackoverflow.com/questions/15676596/what-does-force-ssl-do-in-rails) (redirect to https, mark cookies as secure, enable HSTS etc). You still need to configure your server accordingly to provide the certificates, and the solution depends on your environment.

This app uses Puma as webserver, and you can specify your SSL certificate when running it. Check commands in the docs here: https://github.com/puma/puma

Alternatively, you can set up a server such as [nginx](https://www.nginx.com/) that will work as a proxy to your localhost sever, and enable SSL there.

**Comment by aretsmarvin** [comment]
Thanks. Googled on Puma SSL, getted it to work :)
